receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  otlphttp/logs:
    endpoint: http://tempo:4318
  otlphttp/metrics:
    endpoint: http://mimir-1:8080/otlp/v1/metrics
  otlphttp/traces:
    endpoint: http://tempo:4318

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/metrics]
    traces:
      receivers: [otlp]
      exporters: [otlphttp/traces]
